/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Coupon = IDL.Record({
  'id' : IDL.Text,
  'expiryDate' : IDL.Int,
  'code' : IDL.Text,
  'usedCount' : IDL.Nat,
  'discountPercent' : IDL.Float64,
  'isActive' : IDL.Bool,
  'usageLimit' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TrackingSummary = IDL.Record({
  'trackingNumber' : IDL.Text,
  'totalEntries' : IDL.Nat,
  'lastMessage' : IDL.Text,
  'lastUpdatedAt' : IDL.Int,
  'currentStatus' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CustomOrderRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'designDescription' : IDL.Text,
  'inspirationImageUrl' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'contactNumber' : IDL.Text,
});
export const GalleryPhoto = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'imageUrl' : ExternalBlob,
  'caption' : IDL.Text,
});
export const NewsletterSubscriber = IDL.Record({
  'subscribedAt' : IDL.Int,
  'email' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Text,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'razorpayPaymentId' : IDL.Opt(IDL.Text),
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'couponCode' : IDL.Opt(IDL.Text),
  'trackingNumber' : IDL.Opt(IDL.Text),
  'paymentMethod' : IDL.Text,
  'discountAmount' : IDL.Opt(IDL.Float64),
  'createdAt' : IDL.Int,
  'totalAmount' : IDL.Float64,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'inStock' : IDL.Bool,
  'saleEndDate' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'imageUrl' : ExternalBlob,
  'category' : IDL.Text,
  'salePrice' : IDL.Opt(IDL.Float64),
  'price' : IDL.Float64,
});
export const ProductReview = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'productId' : IDL.Text,
  'reviewerName' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const TrackingEntry = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'trackingNumber' : IDL.Text,
  'updatedAt' : IDL.Int,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addGalleryPhoto' : IDL.Func([ExternalBlob, IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Float64,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Int),
        IDL.Text,
        ExternalBlob,
        IDL.Text,
      ],
      [],
      [],
    ),
  'addReview' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
  'applyCoupon' : IDL.Func([IDL.Text], [Coupon], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllOrders' : IDL.Func([], [], []),
  'createCoupon' : IDL.Func([IDL.Text, IDL.Float64, IDL.Int, IDL.Nat], [], []),
  'deleteCoupon' : IDL.Func([IDL.Text], [], []),
  'deleteGalleryPhoto' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'deleteReview' : IDL.Func([IDL.Text], [], []),
  'deleteTrackingEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'editTrackingEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllTrackingSummaries' : IDL.Func(
      [],
      [IDL.Vec(TrackingSummary)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'getCustomOrders' : IDL.Func([], [IDL.Vec(CustomOrderRequest)], ['query']),
  'getGalleryPhotos' : IDL.Func([], [IDL.Vec(GalleryPhoto)], ['query']),
  'getNewsletterSubscribers' : IDL.Func(
      [],
      [IDL.Vec(NewsletterSubscriber)],
      ['query'],
    ),
  'getOrderByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getOrderByTrackingNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Order)],
      ['query'],
    ),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getPromoBanner' : IDL.Func(
      [],
      [
        IDL.Opt(
          IDL.Record({
            'subText' : IDL.Text,
            'endDate' : IDL.Int,
            'text' : IDL.Text,
            'bgColor' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getReviews' : IDL.Func([IDL.Text], [IDL.Vec(ProductReview)], ['query']),
  'getTrackingHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TrackingEntry)],
      ['query'],
    ),
  'getTrackingInfo' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'history' : IDL.Vec(TrackingEntry),
          'lastUpdatedAt' : IDL.Opt(IDL.Int),
          'currentStatus' : IDL.Opt(IDL.Text),
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(OrderItem),
        IDL.Float64,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPromoBanner' : IDL.Func([IDL.Text, IDL.Text, IDL.Int, IDL.Text], [], []),
  'submitCustomOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
  'updateCoupon' : IDL.Func([IDL.Text, Coupon], [Coupon], []),
  'updateCustomOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateOrderTracking' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Int),
        IDL.Text,
        ExternalBlob,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateTrackingStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [TrackingEntry],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Coupon = IDL.Record({
    'id' : IDL.Text,
    'expiryDate' : IDL.Int,
    'code' : IDL.Text,
    'usedCount' : IDL.Nat,
    'discountPercent' : IDL.Float64,
    'isActive' : IDL.Bool,
    'usageLimit' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TrackingSummary = IDL.Record({
    'trackingNumber' : IDL.Text,
    'totalEntries' : IDL.Nat,
    'lastMessage' : IDL.Text,
    'lastUpdatedAt' : IDL.Int,
    'currentStatus' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CustomOrderRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'designDescription' : IDL.Text,
    'inspirationImageUrl' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'contactNumber' : IDL.Text,
  });
  const GalleryPhoto = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'imageUrl' : ExternalBlob,
    'caption' : IDL.Text,
  });
  const NewsletterSubscriber = IDL.Record({
    'subscribedAt' : IDL.Int,
    'email' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Text,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'razorpayPaymentId' : IDL.Opt(IDL.Text),
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'couponCode' : IDL.Opt(IDL.Text),
    'trackingNumber' : IDL.Opt(IDL.Text),
    'paymentMethod' : IDL.Text,
    'discountAmount' : IDL.Opt(IDL.Float64),
    'createdAt' : IDL.Int,
    'totalAmount' : IDL.Float64,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'inStock' : IDL.Bool,
    'saleEndDate' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'imageUrl' : ExternalBlob,
    'category' : IDL.Text,
    'salePrice' : IDL.Opt(IDL.Float64),
    'price' : IDL.Float64,
  });
  const ProductReview = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'productId' : IDL.Text,
    'reviewerName' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const TrackingEntry = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'trackingNumber' : IDL.Text,
    'updatedAt' : IDL.Int,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addGalleryPhoto' : IDL.Func([ExternalBlob, IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Float64,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Int),
          IDL.Text,
          ExternalBlob,
          IDL.Text,
        ],
        [],
        [],
      ),
    'addReview' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
    'applyCoupon' : IDL.Func([IDL.Text], [Coupon], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllOrders' : IDL.Func([], [], []),
    'createCoupon' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Int, IDL.Nat],
        [],
        [],
      ),
    'deleteCoupon' : IDL.Func([IDL.Text], [], []),
    'deleteGalleryPhoto' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'deleteReview' : IDL.Func([IDL.Text], [], []),
    'deleteTrackingEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'editTrackingEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllTrackingSummaries' : IDL.Func(
        [],
        [IDL.Vec(TrackingSummary)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'getCustomOrders' : IDL.Func([], [IDL.Vec(CustomOrderRequest)], ['query']),
    'getGalleryPhotos' : IDL.Func([], [IDL.Vec(GalleryPhoto)], ['query']),
    'getNewsletterSubscribers' : IDL.Func(
        [],
        [IDL.Vec(NewsletterSubscriber)],
        ['query'],
      ),
    'getOrderByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getOrderByTrackingNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Order)],
        ['query'],
      ),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getPromoBanner' : IDL.Func(
        [],
        [
          IDL.Opt(
            IDL.Record({
              'subText' : IDL.Text,
              'endDate' : IDL.Int,
              'text' : IDL.Text,
              'bgColor' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getReviews' : IDL.Func([IDL.Text], [IDL.Vec(ProductReview)], ['query']),
    'getTrackingHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TrackingEntry)],
        ['query'],
      ),
    'getTrackingInfo' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'history' : IDL.Vec(TrackingEntry),
            'lastUpdatedAt' : IDL.Opt(IDL.Int),
            'currentStatus' : IDL.Opt(IDL.Text),
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(OrderItem),
          IDL.Float64,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPromoBanner' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [],
        [],
      ),
    'submitCustomOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
    'updateCoupon' : IDL.Func([IDL.Text, Coupon], [Coupon], []),
    'updateCustomOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateOrderTracking' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Int),
          IDL.Text,
          ExternalBlob,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateTrackingStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [TrackingEntry],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };