/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Coupon {
  'id' : string,
  'expiryDate' : bigint,
  'code' : string,
  'usedCount' : bigint,
  'discountPercent' : number,
  'isActive' : boolean,
  'usageLimit' : bigint,
}
export interface CustomOrderRequest {
  'id' : string,
  'status' : string,
  'designDescription' : string,
  'inspirationImageUrl' : [] | [ExternalBlob],
  'name' : string,
  'createdAt' : bigint,
  'contactNumber' : string,
}
export type ExternalBlob = Uint8Array;
export interface GalleryPhoto {
  'id' : string,
  'createdAt' : bigint,
  'imageUrl' : ExternalBlob,
  'caption' : string,
}
export interface NewsletterSubscriber {
  'subscribedAt' : bigint,
  'email' : string,
}
export interface Order {
  'id' : string,
  'razorpayPaymentId' : [] | [string],
  'customerName' : string,
  'status' : string,
  'couponCode' : [] | [string],
  'trackingNumber' : [] | [string],
  'paymentMethod' : string,
  'discountAmount' : [] | [number],
  'createdAt' : bigint,
  'totalAmount' : number,
  'address' : string,
  'phone' : string,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'productId' : string,
  'productName' : string,
  'quantity' : bigint,
  'price' : number,
}
export interface Product {
  'id' : string,
  'inStock' : boolean,
  'saleEndDate' : [] | [bigint],
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'imageUrl' : ExternalBlob,
  'category' : string,
  'salePrice' : [] | [number],
  'price' : number,
}
export interface ProductReview {
  'id' : string,
  'createdAt' : bigint,
  'productId' : string,
  'reviewerName' : string,
  'comment' : string,
  'rating' : bigint,
}
export interface TrackingEntry {
  'id' : string,
  'status' : string,
  'trackingNumber' : string,
  'updatedAt' : bigint,
  'message' : string,
}
export interface TrackingSummary {
  'trackingNumber' : string,
  'totalEntries' : bigint,
  'lastMessage' : string,
  'lastUpdatedAt' : bigint,
  'currentStatus' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addGalleryPhoto' : ActorMethod<[ExternalBlob, string], undefined>,
  'addProduct' : ActorMethod<
    [
      string,
      number,
      [] | [number],
      [] | [bigint],
      string,
      ExternalBlob,
      string,
    ],
    undefined
  >,
  'addReview' : ActorMethod<[string, string, bigint, string], undefined>,
  'applyCoupon' : ActorMethod<[string], Coupon>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAllOrders' : ActorMethod<[], undefined>,
  'createCoupon' : ActorMethod<[string, number, bigint, bigint], undefined>,
  'deleteCoupon' : ActorMethod<[string], undefined>,
  'deleteGalleryPhoto' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'deleteReview' : ActorMethod<[string], undefined>,
  'deleteTrackingEntry' : ActorMethod<[string, string], undefined>,
  'editTrackingEntry' : ActorMethod<[string, string, string], undefined>,
  'getAllTrackingSummaries' : ActorMethod<[], Array<TrackingSummary>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoupons' : ActorMethod<[], Array<Coupon>>,
  'getCustomOrders' : ActorMethod<[], Array<CustomOrderRequest>>,
  'getGalleryPhotos' : ActorMethod<[], Array<GalleryPhoto>>,
  'getNewsletterSubscribers' : ActorMethod<[], Array<NewsletterSubscriber>>,
  'getOrderByPhone' : ActorMethod<[string], Array<Order>>,
  'getOrderByTrackingNumber' : ActorMethod<[string], [] | [Order]>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[string], Product>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getPromoBanner' : ActorMethod<
    [],
    [] | [
      {
        'subText' : string,
        'endDate' : bigint,
        'text' : string,
        'bgColor' : string,
      }
    ]
  >,
  'getReviews' : ActorMethod<[string], Array<ProductReview>>,
  'getTrackingHistory' : ActorMethod<[string], Array<TrackingEntry>>,
  'getTrackingInfo' : ActorMethod<
    [string],
    {
      'history' : Array<TrackingEntry>,
      'lastUpdatedAt' : [] | [bigint],
      'currentStatus' : [] | [string],
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Array<OrderItem>,
      number,
      [] | [string],
      [] | [number],
      [] | [string],
    ],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setPromoBanner' : ActorMethod<[string, string, bigint, string], undefined>,
  'submitCustomOrder' : ActorMethod<
    [string, string, string, [] | [ExternalBlob]],
    undefined
  >,
  'subscribeNewsletter' : ActorMethod<[string], undefined>,
  'updateCoupon' : ActorMethod<[string, Coupon], Coupon>,
  'updateCustomOrderStatus' : ActorMethod<[string, string], undefined>,
  'updateOrderStatus' : ActorMethod<[string, string], undefined>,
  'updateOrderTracking' : ActorMethod<[string, string], undefined>,
  'updateProduct' : ActorMethod<
    [
      string,
      string,
      number,
      [] | [number],
      [] | [bigint],
      string,
      ExternalBlob,
      string,
      boolean,
    ],
    undefined
  >,
  'updateTrackingStatus' : ActorMethod<[string, string, string], TrackingEntry>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];